
baseURL = 'https://trajchekrstev.github.io/trajchekrstev-portfolio/'
languageCode = 'en-us'
title = 'Trajche Krstev'
theme = "ananke"
sectionPagesMenu = 'main'
[params]
    linkedin = "https://www.linkedin.com/in/trajche-krstev"
    github = "https://github.com/TrajcheKrstev"
contact_form_action = "https://formspree.io/f/mrbzqbnl"
canonifyURLs = true
relativeURLs = true